import { PrismaClient } from '@prisma/client';
import { Decimal } from '@prisma/client/runtime/library';

const prisma = new PrismaClient();

// Inventory data from client's Excel (cleaned and formatted)
const inventoryData = [
  { name: '3-in-1 Color Laser Printer', unit: 'pcs', quantity: 5, category: 'Printers & Copiers', costPrice: 21154, sellingPrice: 27500 },
  { name: 'Large Format Plotter', unit: 'pcs', quantity: 2, category: 'Printers & Copiers', costPrice: 296154, sellingPrice: 385000 },
  { name: 'Industrial Label Printer', unit: 'pcs', quantity: 3, category: 'Printers & Copiers', costPrice: 71923, sellingPrice: 93500 },
  { name: 'Dot Matrix Printer', unit: 'pcs', quantity: 4, category: 'Printers & Copiers', costPrice: 15231, sellingPrice: 19800 },
  { name: '3D Printer', unit: 'pcs', quantity: 2, category: 'Printers & Copiers', costPrice: 126923, sellingPrice: 165000 },
  { name: 'Gaming Desktop i9/RTX 4090', unit: 'pcs', quantity: 3, category: 'Computers & Peripherals', costPrice: 270769, sellingPrice: 352000 },
  { name: 'All-in-One PC', unit: 'pcs', quantity: 6, category: 'Computers & Peripherals', costPrice: 55000, sellingPrice: 71500 },
  { name: 'Server Rack Unit', unit: 'pcs', quantity: 2, category: 'Computers & Peripherals', costPrice: 186154, sellingPrice: 242000 },
  { name: '4K Monitor 32"', unit: 'pcs', quantity: 10, category: 'Computers & Peripherals', costPrice: 38077, sellingPrice: 49500 },
  { name: 'Mechanical Keyboard', unit: 'pcs', quantity: 15, category: 'Computers & Peripherals', costPrice: 7192, sellingPrice: 9350 },
  { name: 'Wireless Mouse', unit: 'pcs', quantity: 20, category: 'Computers & Peripherals', costPrice: 2115, sellingPrice: 2750 },
  { name: 'External SSD 2TB', unit: 'pcs', quantity: 12, category: 'Computers & Peripherals', costPrice: 15231, sellingPrice: 19800 },
  { name: 'Network Attached Storage', unit: 'pcs', quantity: 4, category: 'Computers & Peripherals', costPrice: 63462, sellingPrice: 82500 },
  { name: 'Document Scanner ADF', unit: 'pcs', quantity: 5, category: 'Imaging & Scanning', costPrice: 46538, sellingPrice: 60500 },
  { name: 'Flatbed Scanner A3', unit: 'pcs', quantity: 3, category: 'Imaging & Scanning', costPrice: 32154, sellingPrice: 41800 },
  { name: 'DSLR Camera', unit: 'pcs', quantity: 4, category: 'Imaging & Scanning', costPrice: 71923, sellingPrice: 93500 },
  { name: 'Drone with 4K Camera', unit: 'pcs', quantity: 2, category: 'Imaging & Scanning', costPrice: 211538, sellingPrice: 275000 },
  { name: 'Portable Photo Printer', unit: 'pcs', quantity: 8, category: 'Imaging & Scanning', costPrice: 10154, sellingPrice: 13200 },
  { name: 'Wireless Router', unit: 'pcs', quantity: 10, category: 'Networking & Communication', costPrice: 7615, sellingPrice: 9900 },
  { name: 'Network Switch 48-port', unit: 'pcs', quantity: 3, category: 'Networking & Communication', costPrice: 35538, sellingPrice: 46200 },
  { name: 'VoIP Phone System', unit: 'pcs', quantity: 6, category: 'Networking & Communication', costPrice: 23692, sellingPrice: 30800 },
  { name: 'Fiber Optic Modem', unit: 'pcs', quantity: 5, category: 'Networking & Communication', costPrice: 12692, sellingPrice: 16500 },
  { name: '5G Hotspot Device', unit: 'pcs', quantity: 7, category: 'Networking & Communication', costPrice: 18615, sellingPrice: 24200 },
  { name: 'Paper Shredder Heavy-duty', unit: 'pcs', quantity: 4, category: 'Office Machinery & Supplies', costPrice: 27077, sellingPrice: 35200 },
  { name: 'Currency Counting Machine', unit: 'pcs', quantity: 3, category: 'Office Machinery & Supplies', costPrice: 46538, sellingPrice: 60500 },
  { name: 'Electronic Safe', unit: 'pcs', quantity: 5, category: 'Office Machinery & Supplies', costPrice: 33846, sellingPrice: 44000 },
  { name: 'Standing Desk Electric', unit: 'pcs', quantity: 6, category: 'Office Machinery & Supplies', costPrice: 63462, sellingPrice: 82500 },
  { name: 'Conference System with Mic', unit: 'pcs', quantity: 2, category: 'Office Machinery & Supplies', costPrice: 101538, sellingPrice: 132000 },
  { name: 'Online UPS 3kVA', unit: 'pcs', quantity: 4, category: 'Power & Electrical', costPrice: 80385, sellingPrice: 104500 },
  { name: 'Voltage Stabilizer 10kVA', unit: 'pcs', quantity: 2, category: 'Power & Electrical', costPrice: 152308, sellingPrice: 198000 },
  { name: 'Solar Inverter 5kW', unit: 'pcs', quantity: 3, category: 'Power & Electrical', costPrice: 177692, sellingPrice: 231000 },
  { name: 'Portable Power Station', unit: 'pcs', quantity: 8, category: 'Power & Electrical', costPrice: 55000, sellingPrice: 71500 },
  { name: 'Surge Protector Strip', unit: 'pcs', quantity: 25, category: 'Power & Electrical', costPrice: 2962, sellingPrice: 3850 },
  { name: '4K CCTV Camera Dome', unit: 'pcs', quantity: 12, category: 'Security & Surveillance', costPrice: 15231, sellingPrice: 19800 },
  { name: 'NVR 16-Channel', unit: 'pcs', quantity: 4, category: 'Security & Surveillance', costPrice: 44000, sellingPrice: 57200 },
  { name: 'Biometric Access Control', unit: 'pcs', quantity: 6, category: 'Security & Surveillance', costPrice: 40615, sellingPrice: 52800 },
  { name: 'Metal Detector', unit: 'pcs', quantity: 2, category: 'Security & Surveillance', costPrice: 71923, sellingPrice: 93500 },
  { name: 'Fire Alarm Control Panel', unit: 'pcs', quantity: 3, category: 'Security & Surveillance', costPrice: 101538, sellingPrice: 132000 },
  { name: '4K Laser Projector', unit: 'pcs', quantity: 3, category: 'Audio-Visual & Presentation', costPrice: 465385, sellingPrice: 605000 },
  { name: 'Interactive Whiteboard', unit: 'pcs', quantity: 4, category: 'Audio-Visual & Presentation', costPrice: 152308, sellingPrice: 198000 },
  { name: 'PA System 2000W', unit: 'pcs', quantity: 2, category: 'Audio-Visual & Presentation', costPrice: 177692, sellingPrice: 231000 },
  { name: 'Wireless Microphone System', unit: 'pcs', quantity: 8, category: 'Audio-Visual & Presentation', costPrice: 27077, sellingPrice: 35200 },
  { name: 'Studio Monitor Speakers', unit: 'pcs', quantity: 6, category: 'Audio-Visual & Presentation', costPrice: 38077, sellingPrice: 49500 },
  { name: 'Barcode Scanner Industrial', unit: 'pcs', quantity: 7, category: 'Miscellaneous Technology', costPrice: 23692, sellingPrice: 30800 },
  { name: 'RFID Inventory System', unit: 'pcs', quantity: 3, category: 'Miscellaneous Technology', costPrice: 165000, sellingPrice: 214500 },
  { name: 'Digital Signage Display 55"', unit: 'pcs', quantity: 5, category: 'Miscellaneous Technology', costPrice: 114231, sellingPrice: 148500 },
  { name: 'Virtual Reality Headset', unit: 'pcs', quantity: 6, category: 'Miscellaneous Technology', costPrice: 55000, sellingPrice: 71500 },
  { name: 'Robotics Process Automation Kit', unit: 'pcs', quantity: 2, category: 'Miscellaneous Technology', costPrice: 719231, sellingPrice: 935000 },
  { name: 'VGA Cable', unit: 'pcs', quantity: 18, category: 'Computer Accessories', costPrice: 110, sellingPrice: 143 },
  { name: 'Power Cable Desktop', unit: 'pcs', quantity: 83, category: 'Computer Accessories', costPrice: 127, sellingPrice: 165 },
  { name: 'Power Cable Laptop', unit: 'pcs', quantity: 16, category: 'Computer Accessories', costPrice: 127, sellingPrice: 165 },
  { name: 'S-Tek Computer Tool Kit 50pcs', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 8038, sellingPrice: 10450 },
  { name: 'CRYSTAL Computer Tool Kit 56pcs', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 8038, sellingPrice: 10450 },
  { name: 'CRYSTAL Computer Tool Kit 10pcs', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 8038, sellingPrice: 10450 },
  { name: 'Poso Maintenance Tool Kit', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 3892, sellingPrice: 5060 },
  { name: 'Desktop HDD 1TB Internal', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 3892, sellingPrice: 5060 },
  { name: 'Desktop HDD 500GB Internal', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 2538, sellingPrice: 3300 },
  { name: 'Laptop 2TB Desktop Internal Video', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 8038, sellingPrice: 10450 },
  { name: 'Desktop HDD 2TB Internal', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 8038, sellingPrice: 10450 },
  { name: 'Telephone Box Small', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 2708, sellingPrice: 3520 },
  { name: 'Telephone Box', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 2538, sellingPrice: 3300 },
  { name: 'Telephone Box Ethio Telecom', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 1862, sellingPrice: 2420 },
  { name: 'Dish Connector', unit: 'pcs', quantity: 36, category: 'Computer Accessories', costPrice: 8, sellingPrice: 11 },
  { name: 'Laptop HDD 1TB Internal', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 4231, sellingPrice: 5500 },
  { name: 'Laptop HDD 500GB Internal', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 1565, sellingPrice: 2035 },
  { name: 'External DVD-RW Drive', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 1523, sellingPrice: 1980 },
  { name: 'Laptop Screen 10"', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 1269, sellingPrice: 1650 },
  { name: 'Internal DVD ROM', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 1692, sellingPrice: 2200 },
  { name: 'Internal DVD-RW Desktop', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 1692, sellingPrice: 2200 },
  { name: 'Laptop Screen 15.6" Altera Slim', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 5500, sellingPrice: 7150 },
  { name: 'Laptop Screen 15.6" LED', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 5500, sellingPrice: 7150 },
  { name: 'Laptop Adapter Assess', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Laptop Adapter Lenovo', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 1523, sellingPrice: 1980 },
  { name: 'External Hard Disk 1TB', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 6769, sellingPrice: 8800 },
  { name: 'External Hard Disk 2TB', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 13962, sellingPrice: 18150 },
  { name: 'Laptop Adapter Toshiba', unit: 'pcs', quantity: 9, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Laptop Adapter Dell', unit: 'pcs', quantity: 6, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Laptop Adapter HP', unit: 'pcs', quantity: 29, category: 'Computer Accessories', costPrice: 1100, sellingPrice: 1430 },
  { name: 'External SSD Case 2.5"', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 550, sellingPrice: 715 },
  { name: 'Blower RYODEL Large', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 2369, sellingPrice: 3080 },
  { name: 'Blower Power', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 1354, sellingPrice: 1760 },
  { name: 'Flash Dual Type-C 32GB', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Flash Dual 32GB', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'Flash Dual 64GB', unit: 'pcs', quantity: 11, category: 'Computer Accessories', costPrice: 719, sellingPrice: 935 },
  { name: 'Camera Memory 64GB', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 931, sellingPrice: 1210 },
  { name: 'Mobile/Camera Memory 128GB', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 1100, sellingPrice: 1430 },
  { name: 'Mobile/Camera Memory 64GB', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 381, sellingPrice: 495 },
  { name: 'Flash 64GB T-Max', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 719, sellingPrice: 935 },
  { name: 'Flash 32GB SanDisk', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'Camera Memory 64GB', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 329, sellingPrice: 429 },
  { name: 'Camera Memory 128GB', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Screen Cleaner', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 212, sellingPrice: 275 },
  { name: 'USB to RS232 Converter', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'Type-C to 8-in-1 Adapter', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 1862, sellingPrice: 2420 },
  { name: 'Type-C to 11-in-1 Adapter', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 2708, sellingPrice: 3520 },
  { name: 'Type-C to 4-in-1 Adapter', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 2115, sellingPrice: 2750 },
  { name: 'Display Port Adapter', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 381, sellingPrice: 495 },
  { name: 'VGA to Display Port Converter', unit: 'pcs', quantity: 10, category: 'Computer Accessories', costPrice: 508, sellingPrice: 660 },
  { name: 'USB to VGA Converter', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 550, sellingPrice: 715 },
  { name: 'Mini Display Port Adapter', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 550, sellingPrice: 715 },
  { name: 'Display Port to HDMI Adapter', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'HDMI Extender', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 1523, sellingPrice: 1980 },
  { name: 'VGA to HDMI', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 381, sellingPrice: 495 },
  { name: 'HDMI to VGA with Audio Converter', unit: 'pcs', quantity: 5, category: 'Computer Accessories', costPrice: 846, sellingPrice: 1100 },
  { name: 'HDMI to USB Converter', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 313, sellingPrice: 407 },
  { name: 'USB Hub 8-port 3.0', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 677, sellingPrice: 880 },
  { name: 'USB Hub 4-port 2.0', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 550, sellingPrice: 715 },
  { name: 'USB Hub and Card Reader', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'HDMI Cable 20m', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 931, sellingPrice: 1210 },
  { name: 'HDMI Cable 10m', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 491, sellingPrice: 638 },
  { name: 'HDMI Cable 5m', unit: 'pcs', quantity: 5, category: 'Computer Accessories', costPrice: 188, sellingPrice: 242 },
  { name: 'HDMI to Jack Cable', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 158, sellingPrice: 204 },
  { name: 'HDMI Cable 1.5m', unit: 'pcs', quantity: 11, category: 'Computer Accessories', costPrice: 110, sellingPrice: 143 },
  { name: 'USB Printer Cable 1.5m', unit: 'pcs', quantity: 15, category: 'Computer Accessories', costPrice: 55, sellingPrice: 72 },
  { name: 'USB Printer Cable 5m', unit: 'pcs', quantity: 5, category: 'Computer Accessories', costPrice: 85, sellingPrice: 110 },
  { name: 'USB Printer Cable 10m', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 762, sellingPrice: 990 },
  { name: 'Wireless Mouse Enet', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 550, sellingPrice: 715 },
  { name: 'Mercury Wired Mouse', unit: 'pcs', quantity: 5, category: 'Computer Accessories', costPrice: 220, sellingPrice: 286 },
  { name: 'Targus Wired Mouse', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 220, sellingPrice: 286 },
  { name: 'Wired Mouse Enet', unit: 'pcs', quantity: 18, category: 'Computer Accessories', costPrice: 212, sellingPrice: 275 },
  { name: 'Intex Wired Mouse', unit: 'pcs', quantity: 10, category: 'Computer Accessories', costPrice: 212, sellingPrice: 275 },
  { name: 'Wireless Dell Mouse', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'Dell Mouse Wired', unit: 'pcs', quantity: 48, category: 'Computer Accessories', costPrice: 203, sellingPrice: 264 },
  { name: 'Max Day Battery Charger', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'Dust Cover Desktop', unit: 'pcs', quantity: 5, category: 'Computer Accessories', costPrice: 212, sellingPrice: 275 },
  { name: 'RAM Laptop 4GB', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'RAM Laptop 8GB', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 2115, sellingPrice: 2750 },
  { name: 'RAM Laptop 32GB', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 3808, sellingPrice: 4950 },
  { name: 'SSD 512GB', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 2962, sellingPrice: 3850 },
  { name: 'SSD 1TB', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 5923, sellingPrice: 7700 },
  { name: 'SATA 256GB', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 1862, sellingPrice: 2420 },
  { name: 'CMOS Battery', unit: 'pcs', quantity: 38, category: 'Computer Accessories', costPrice: 64, sellingPrice: 83 },
  { name: 'Celeron Motherboard', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 635, sellingPrice: 825 },
  { name: 'Celeron Screen', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 212, sellingPrice: 275 },
  { name: 'Power Supply Intex Small', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 212, sellingPrice: 275 },
  { name: 'Power Supply Intex', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Power Supply 3040', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 2115, sellingPrice: 2750 },
  { name: 'Power Supply 3020 6-pin/8-pin', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 2708, sellingPrice: 3520 },
  { name: 'Power Supply Dell', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 2200, sellingPrice: 2860 },
  { name: 'Speaker Desktop Small', unit: 'pcs', quantity: 7, category: 'Computer Accessories', costPrice: 508, sellingPrice: 660 },
  { name: 'Speaker Dell Computer Large', unit: 'pcs', quantity: 8, category: 'Computer Accessories', costPrice: 508, sellingPrice: 660 },
  { name: 'Keyboard Dell Original Desktop', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 2115, sellingPrice: 2750 },
  { name: 'Mouse Wireless Logitech', unit: 'pcs', quantity: 12, category: 'Computer Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'Dell Keyboard', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 1058, sellingPrice: 1375 },
  { name: 'Laptop Keyboard', unit: 'pcs', quantity: 9, category: 'Computer Accessories', costPrice: 2962, sellingPrice: 3850 },
  { name: 'Wireless Keyboard Mophi', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 2708, sellingPrice: 3520 },
  { name: 'Flexible Keyboard', unit: 'pcs', quantity: 2, category: 'Computer Accessories', costPrice: 677, sellingPrice: 880 },
  { name: 'Wired Mouse M90', unit: 'pcs', quantity: 11, category: 'Computer Accessories', costPrice: 152, sellingPrice: 198 },
  { name: 'HP Wired Mouse', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'Lenovo Wired Mouse', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 508, sellingPrice: 660 },
  { name: 'Lenovo Wireless Mouse', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 635, sellingPrice: 825 },
  { name: 'CD-R', unit: 'pack', quantity: 4, category: 'Computer Accessories', costPrice: 1904, sellingPrice: 2475 },
  { name: 'DVD-R', unit: 'pack', quantity: 4, category: 'Computer Accessories', costPrice: 2327, sellingPrice: 3025 },
  { name: 'Alarm Big', unit: 'pcs', quantity: 1, category: 'Computer Accessories', costPrice: 5923, sellingPrice: 7700 },
  { name: 'All-in-One Card Reader', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 1565, sellingPrice: 2035 },
  { name: 'M.2 NVMe SSD 1TB', unit: 'pcs', quantity: 15, category: 'Computer Accessories', costPrice: 7192, sellingPrice: 9350 },
  { name: 'M.2 NVMe SSD 2TB', unit: 'pcs', quantity: 8, category: 'Computer Accessories', costPrice: 13538, sellingPrice: 17600 },
  { name: 'External SSD 1TB USB 3.2', unit: 'pcs', quantity: 12, category: 'Computer Accessories', costPrice: 7615, sellingPrice: 9900 },
  { name: 'External SSD 2TB USB-C', unit: 'pcs', quantity: 6, category: 'Computer Accessories', costPrice: 15654, sellingPrice: 20350 },
  { name: 'NAS HDD 4TB 7200RPM', unit: 'pcs', quantity: 5, category: 'Computer Accessories', costPrice: 10154, sellingPrice: 13200 },
  { name: 'SSD Enclosure USB 3.1', unit: 'pcs', quantity: 20, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Portable SSD 500GB', unit: 'pcs', quantity: 10, category: 'Computer Accessories', costPrice: 5500, sellingPrice: 7150 },
  { name: 'RAID Controller Card', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 8038, sellingPrice: 10450 },
  { name: 'DDR4 RAM 16GB 3200MHz', unit: 'pcs', quantity: 25, category: 'Computer Accessories', costPrice: 3808, sellingPrice: 4950 },
  { name: 'DDR5 RAM 32GB 5200MHz', unit: 'pcs', quantity: 8, category: 'Computer Accessories', costPrice: 10154, sellingPrice: 13200 },
  { name: 'SODIMM DDR4 8GB 2666MHz', unit: 'pcs', quantity: 18, category: 'Computer Accessories', costPrice: 2369, sellingPrice: 3080 },
  { name: 'SODIMM DDR5 16GB 4800MHz', unit: 'pcs', quantity: 10, category: 'Computer Accessories', costPrice: 5500, sellingPrice: 7150 },
  { name: 'ECC Server RAM 32GB', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 15231, sellingPrice: 19800 },
  { name: 'RAM Cooler with Heat Spreader', unit: 'pcs', quantity: 15, category: 'Computer Accessories', costPrice: 719, sellingPrice: 935 },
  { name: 'USB-C Cable 100W 2m', unit: 'pcs', quantity: 50, category: 'Computer Accessories', costPrice: 550, sellingPrice: 715 },
  { name: 'Thunderbolt 4 Cable 1m', unit: 'pcs', quantity: 12, category: 'Computer Accessories', costPrice: 2708, sellingPrice: 3520 },
  { name: 'DisplayPort 1.4 Cable 3m', unit: 'pcs', quantity: 30, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Optical HDMI Cable 15m', unit: 'pcs', quantity: 8, category: 'Computer Accessories', costPrice: 3808, sellingPrice: 4950 },
  { name: 'Ethernet Cat8 Cable 10m', unit: 'pcs', quantity: 25, category: 'Computer Accessories', costPrice: 1523, sellingPrice: 1980 },
  { name: 'KVM Switch 4-port', unit: 'pcs', quantity: 6, category: 'Computer Accessories', costPrice: 5500, sellingPrice: 7150 },
  { name: 'Docking Station USB-C Dual 4K', unit: 'pcs', quantity: 10, category: 'Computer Accessories', costPrice: 10577, sellingPrice: 13750 },
  { name: 'Fiber Optic HDMI Converter', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 18615, sellingPrice: 24200 },
  { name: 'Mechanical Gaming Keyboard', unit: 'pcs', quantity: 15, category: 'Computer Accessories', costPrice: 4654, sellingPrice: 6050 },
  { name: 'Ergonomic Wireless Keyboard', unit: 'pcs', quantity: 12, category: 'Computer Accessories', costPrice: 3538, sellingPrice: 4620 },
  { name: 'Gaming Mouse 16000DPI', unit: 'pcs', quantity: 20, category: 'Computer Accessories', costPrice: 2962, sellingPrice: 3850 },
  { name: 'Vertical Ergonomic Mouse', unit: 'pcs', quantity: 8, category: 'Computer Accessories', costPrice: 2369, sellingPrice: 3080 },
  { name: 'Drawing Tablet 10"', unit: 'pcs', quantity: 6, category: 'Computer Accessories', costPrice: 7192, sellingPrice: 9350 },
  { name: 'Trackball Mouse', unit: 'pcs', quantity: 10, category: 'Computer Accessories', costPrice: 2708, sellingPrice: 3520 },
  { name: 'Barcode Scanner Wireless', unit: 'pcs', quantity: 5, category: 'Computer Accessories', costPrice: 10154, sellingPrice: 13200 },
  { name: 'Foot Pedal Switch', unit: 'pcs', quantity: 8, category: 'Computer Accessories', costPrice: 2115, sellingPrice: 2750 },
  { name: 'Laptop Cooling Pad', unit: 'pcs', quantity: 15, category: 'Computer Accessories', costPrice: 1523, sellingPrice: 1980 },
  { name: 'CPU Air Cooler', unit: 'pcs', quantity: 12, category: 'Computer Accessories', costPrice: 2962, sellingPrice: 3850 },
  { name: 'AIO Liquid Cooler 240mm', unit: 'pcs', quantity: 8, category: 'Computer Accessories', costPrice: 7192, sellingPrice: 9350 },
  { name: 'PSU 80+ Gold 850W', unit: 'pcs', quantity: 6, category: 'Computer Accessories', costPrice: 9731, sellingPrice: 12650 },
  { name: 'Uninterruptible Power Supply', unit: 'pcs', quantity: 10, category: 'Computer Accessories', costPrice: 6346, sellingPrice: 8250 },
  { name: 'Voltage Stabilizer 5kVA', unit: 'pcs', quantity: 4, category: 'Computer Accessories', costPrice: 21154, sellingPrice: 27500 },
  { name: 'Anti-static Mat', unit: 'pcs', quantity: 20, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'ESD Wrist Strap', unit: 'pcs', quantity: 30, category: 'Computer Accessories', costPrice: 296, sellingPrice: 385 },
  { name: 'Wi-Fi 6 Router', unit: 'pcs', quantity: 12, category: 'Computer Accessories', costPrice: 8038, sellingPrice: 10450 },
  { name: 'Mesh Wi-Fi System 3-pack', unit: 'pcs', quantity: 5, category: 'Computer Accessories', costPrice: 18615, sellingPrice: 24200 },
  { name: 'PoE Injector', unit: 'pcs', quantity: 15, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Network Switch 24-port Gigabit', unit: 'pcs', quantity: 8, category: 'Computer Accessories', costPrice: 12692, sellingPrice: 16500 },
  { name: 'Powerline Adapter 1200Mbps', unit: 'pcs', quantity: 10, category: 'Computer Accessories', costPrice: 3808, sellingPrice: 4950 },
  { name: 'USB Wi-Fi Adapter AC1900', unit: 'pcs', quantity: 18, category: 'Computer Accessories', costPrice: 2708, sellingPrice: 3520 },
  { name: 'RJ45 Crimping Tool', unit: 'pcs', quantity: 6, category: 'Computer Accessories', costPrice: 2369, sellingPrice: 3080 },
  { name: 'Network Cable Tester', unit: 'pcs', quantity: 8, category: 'Computer Accessories', costPrice: 1269, sellingPrice: 1650 },
  { name: 'USB Condenser Microphone', unit: 'pcs', quantity: 12, category: 'Computer Accessories', costPrice: 3808, sellingPrice: 4950 },
  { name: 'Webcam 4K with Privacy Shutter', unit: 'pcs', quantity: 15, category: 'Computer Accessories', costPrice: 7192, sellingPrice: 9350 },
  { name: 'Capture Card 4K 60fps', unit: 'pcs', quantity: 5, category: 'Computer Accessories', costPrice: 15231, sellingPrice: 19800 },
  { name: 'USB Audio Interface', unit: 'pcs', quantity: 8, category: 'Computer Accessories', costPrice: 10154, sellingPrice: 13750 },
  { name: 'Headphone Amplifier', unit: 'pcs', quantity: 6, category: 'Computer Accessories', costPrice: 5500, sellingPrice: 7150 },
  { name: 'Monitor Arm Dual', unit: 'pcs', quantity: 10, category: 'Computer Accessories', costPrice: 7192, sellingPrice: 9350 },
  { name: 'Privacy Screen Filter 15.6"', unit: 'pcs', quantity: 20, category: 'Computer Accessories', costPrice: 1523, sellingPrice: 1980 },
  { name: 'Green Screen Kit', unit: 'pcs', quantity: 5, category: 'Computer Accessories', costPrice: 6346, sellingPrice: 8250 },
  { name: 'Precision Screwdriver Set 64pcs', unit: 'pcs', quantity: 15, category: 'Computer Accessories', costPrice: 2962, sellingPrice: 3850 },
  { name: 'Electronics Soldering Station', unit: 'pcs', quantity: 8, category: 'Computer Accessories', costPrice: 5500, sellingPrice: 7150 },
  { name: 'Thermal Paste 10g', unit: 'pcs', quantity: 30, category: 'Computer Accessories', costPrice: 381, sellingPrice: 495 },
  { name: 'SMD Rework Station', unit: 'pcs', quantity: 3, category: 'Computer Accessories', costPrice: 38077, sellingPrice: 49500 },
  { name: 'Multimeter Digital', unit: 'pcs', quantity: 12, category: 'Computer Accessories', costPrice: 2115, sellingPrice: 2750 },
  { name: 'PCB Holder with Magnifier', unit: 'pcs', quantity: 10, category: 'Computer Accessories', costPrice: 2708, sellingPrice: 3520 },
  { name: 'Heat Gun 1000W', unit: 'pcs', quantity: 6, category: 'Computer Accessories', costPrice: 3808, sellingPrice: 4950 },
  { name: 'Anti-static Brushes', unit: 'set', quantity: 25, category: 'Computer Accessories', costPrice: 719, sellingPrice: 935 },
  { name: 'Tablet Stand Adjustable', unit: 'pcs', quantity: 20, category: 'Computer Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Phone Holder Car Mount', unit: 'pcs', quantity: 25, category: 'Computer Accessories', costPrice: 719, sellingPrice: 935 },
  { name: 'Wireless Charger 15W', unit: 'pcs', quantity: 18, category: 'Computer Accessories', costPrice: 2115, sellingPrice: 2750 },
  { name: 'Fast Charger 65W GaN', unit: 'pcs', quantity: 15, category: 'Computer Accessories', costPrice: 2708, sellingPrice: 3520 },
  { name: 'USB-C Hub 7-in-1 for Tablet', unit: 'pcs', quantity: 12, category: 'Computer Accessories', costPrice: 3808, sellingPrice: 4950 },
  { name: 'Laptop Sleeve 15.6" Waterproof', unit: 'pcs', quantity: 30, category: 'Computer Accessories', costPrice: 1523, sellingPrice: 1980 },
  { name: 'Backpack Laptop Compartment', unit: 'pcs', quantity: 15, category: 'Computer Accessories', costPrice: 3808, sellingPrice: 4950 },
  { name: 'Screen Protector Kit', unit: 'pcs', quantity: 50, category: 'Computer Accessories', costPrice: 550, sellingPrice: 715 },
  { name: 'Paper Tray 3 set', unit: 'pcs', quantity: 2, category: 'Stationery Items', costPrice: 1185, sellingPrice: 1540 },
  { name: 'Paper Roadmap A4', unit: 'reem', quantity: 3, category: 'Stationery Items', costPrice: 719, sellingPrice: 935 },
  { name: 'Paper Gold A4', unit: 'reem', quantity: 2, category: 'Stationery Items', costPrice: 804, sellingPrice: 1045 },
  { name: 'Color Paper (Spectra)', unit: 'reem', quantity: 5, category: 'Stationery Items', costPrice: 385, sellingPrice: 501 },
  { name: 'Set Square', unit: 'pcs', quantity: 1, category: 'Stationery Items', costPrice: 85, sellingPrice: 110 },
  { name: 'Claro Pen', unit: 'pcs', quantity: 15, category: 'Stationery Items', costPrice: 592, sellingPrice: 770 },
  { name: 'Cello Pen Blue', unit: 'pak', quantity: 31, category: 'Stationery Items', costPrice: 592, sellingPrice: 770 },
  { name: 'Bic Pen', unit: 'pak', quantity: 1, category: 'Stationery Items', costPrice: 846, sellingPrice: 1100 },
  { name: 'Black Cello Pen', unit: 'pak', quantity: 1, category: 'Stationery Items', costPrice: 592, sellingPrice: 770 },
  { name: 'Fastener', unit: 'pak', quantity: 12, category: 'Stationery Items', costPrice: 51, sellingPrice: 66 },
  { name: 'White Board Marker', unit: 'pak', quantity: 2, category: 'Stationery Items', costPrice: 465, sellingPrice: 605 },
  { name: 'Puncher DP-520', unit: 'pcs', quantity: 9, category: 'Stationery Items', costPrice: 296, sellingPrice: 385 },
  { name: 'Puncher P-720', unit: 'pcs', quantity: 8, category: 'Stationery Items', costPrice: 465, sellingPrice: 605 },
  { name: 'Stapler Kangaro DS-435', unit: 'pcs', quantity: 4, category: 'Stationery Items', costPrice: 296, sellingPrice: 385 },
  { name: 'Stapler Kangaro DS-335', unit: 'pcs', quantity: 13, category: 'Stationery Items', costPrice: 212, sellingPrice: 275 },
  { name: 'Staples Wire Large Kangaro', unit: 'pak', quantity: 13, category: 'Stationery Items', costPrice: 110, sellingPrice: 143 },
  { name: 'Staples Wire 369', unit: 'pak', quantity: 1, category: 'Stationery Items', costPrice: 296, sellingPrice: 385 },
  { name: 'Staples Wire Heavy Duty', unit: 'pak', quantity: 1, category: 'Stationery Items', costPrice: 381, sellingPrice: 495 },
  { name: 'Flip Chart', unit: 'pak', quantity: 2, category: 'Stationery Items', costPrice: 238, sellingPrice: 308 },
  { name: 'Ring 8mm', unit: 'pak', quantity: 4, category: 'Stationery Items', costPrice: 931, sellingPrice: 1210 },
  { name: 'Ring 10mm', unit: 'pak', quantity: 2, category: 'Stationery Items', costPrice: 1134, sellingPrice: 1474 },
  { name: 'Ring 6mm', unit: 'pak', quantity: 1, category: 'Stationery Items', costPrice: 677, sellingPrice: 880 },
  { name: 'Ring 12mm', unit: 'pak', quantity: 1, category: 'Stationery Items', costPrice: 931, sellingPrice: 1210 },
  { name: 'Ring 18mm', unit: 'pak', quantity: 1, category: 'Stationery Items', costPrice: 1058, sellingPrice: 1375 },
  { name: 'Scotch Tape', unit: 'pcs', quantity: 36, category: 'Stationery Items', costPrice: 21, sellingPrice: 28 },
  { name: 'Plaster Big', unit: 'pcs', quantity: 3, category: 'Stationery Items', costPrice: 296, sellingPrice: 385 },
  { name: 'Sky Soap', unit: 'pcs', quantity: 27, category: 'Stationery Items', costPrice: 55, sellingPrice: 72 },
  { name: 'Okay Soap 230gm', unit: 'pcs', quantity: 50, category: 'Stationery Items', costPrice: 46, sellingPrice: 60 },
  { name: 'Hand Liquid Soap', unit: 'pcs', quantity: 12, category: 'Stationery Items', costPrice: 64, sellingPrice: 83 },
  { name: 'Lifebuoy 70gm', unit: 'pcs', quantity: 100, category: 'Stationery Items', costPrice: 32, sellingPrice: 41 },
  { name: 'Lifebuoy 150gm', unit: 'pcs', quantity: 7, category: 'Stationery Items', costPrice: 83, sellingPrice: 108 },
  { name: 'Hand Battery Big', unit: 'pcs', quantity: 2, category: 'Stationery Items', costPrice: 1946, sellingPrice: 2530 },
  { name: 'Foxxa Small', unit: 'pcs', quantity: 12, category: 'Stationery Items', costPrice: 30, sellingPrice: 39 },
  { name: 'Foxxa Big', unit: 'pcs', quantity: 12, category: 'Stationery Items', costPrice: 38, sellingPrice: 49 },
  { name: 'Khaki Post A5 Size', unit: 'reem', quantity: 5, category: 'Stationery Items', costPrice: 296, sellingPrice: 385 },
  { name: 'Calculator CASIO DJ-120D 3Zero', unit: 'pcs', quantity: 13, category: 'Stationery Items', costPrice: 2115, sellingPrice: 2750 },
  { name: 'Calculator CASIO DJ-120TW 2Zero', unit: 'pcs', quantity: 3, category: 'Stationery Items', costPrice: 1523, sellingPrice: 1980 },
  { name: 'Fixer 0.7', unit: 'pcs', quantity: 18, category: 'Stationery Items', costPrice: 25, sellingPrice: 33 },
  { name: 'Color Paper A4 Renbo', unit: 'reem', quantity: 2, category: 'Stationery Items', costPrice: 338, sellingPrice: 440 },
  { name: 'Carbo 8000H', unit: 'reem', quantity: 10, category: 'Stationery Items', costPrice: 542, sellingPrice: 704 },
  { name: 'Transparent Cover', unit: 'reem', quantity: 4, category: 'Stationery Items', costPrice: 423, sellingPrice: 550 },
  { name: 'Hard Cover', unit: 'reem', quantity: 5, category: 'Stationery Items', costPrice: 423, sellingPrice: 550 },
  { name: 'ID Card', unit: 'pcs', quantity: 200, category: 'Stationery Items', costPrice: 19, sellingPrice: 25 },
  { name: 'Black Board Duster Omega', unit: 'pak', quantity: 2, category: 'Stationery Items', costPrice: 381, sellingPrice: 495 },
  { name: 'UHU Glue', unit: 'pcs', quantity: 21, category: 'Stationery Items', costPrice: 51, sellingPrice: 66 },
  { name: 'Khaki Post A4 Size', unit: 'reem', quantity: 7, category: 'Stationery Items', costPrice: 381, sellingPrice: 495 },
  { name: 'Khaki Post A3 Size', unit: 'reem', quantity: 5, category: 'Stationery Items', costPrice: 465, sellingPrice: 605 },
  { name: 'Stamp Ink', unit: 'pcs', quantity: 18, category: 'Stationery Items', costPrice: 38, sellingPrice: 49 },
  { name: 'Stamp Pad', unit: 'pcs', quantity: 42, category: 'Stationery Items', costPrice: 64, sellingPrice: 83 },
  { name: 'Notebook 5x8 Small', unit: 'pcs', quantity: 30, category: 'Stationery Items', costPrice: 38, sellingPrice: 49 },
  { name: 'Notebook 7X9', unit: 'pcs', quantity: 120, category: 'Stationery Items', costPrice: 64, sellingPrice: 83 },
  { name: 'Exercise Book 50 Sheet', unit: 'pcs', quantity: 7, category: 'Stationery Items', costPrice: 68, sellingPrice: 88 },
  { name: 'Fluid Bottle', unit: 'pcs', quantity: 11, category: 'Stationery Items', costPrice: 23, sellingPrice: 30 },
  { name: 'White Post', unit: 'pak', quantity: 7, category: 'Stationery Items', costPrice: 161, sellingPrice: 209 },
  { name: 'CM Mastish 43', unit: 'pcs', quantity: 1, category: 'Stationery Items', costPrice: 423, sellingPrice: 550 },
  { name: 'OPC', unit: 'pcs', quantity: 2, category: 'Stationery Items', costPrice: 592, sellingPrice: 770 },
  { name: 'Box File Kent Small', unit: 'pcs', quantity: 23, category: 'Stationery Items', costPrice: 161, sellingPrice: 209 },
  { name: 'Box File KENT', unit: 'pcs', quantity: 53, category: 'Stationery Items', costPrice: 119, sellingPrice: 154 },
  { name: 'Paper Clip Agraf 33mm', unit: 'pak', quantity: 16, category: 'Stationery Items', costPrice: 27, sellingPrice: 35 },
  { name: 'Paper Clip Agraf 50mm', unit: 'pak', quantity: 3, category: 'Stationery Items', costPrice: 42, sellingPrice: 55 },
  { name: 'Registration Book Importer 25x35', unit: 'pcs', quantity: 28, category: 'Stationery Items', costPrice: 406, sellingPrice: 528 },
  { name: 'Registration Book Importer 20x30', unit: 'pcs', quantity: 6, category: 'Stationery Items', costPrice: 281, sellingPrice: 363 },
  { name: 'Registration Book Local Small', unit: 'pcs', quantity: 1, category: 'Stationery Items', costPrice: 381, sellingPrice: 495 },
  { name: 'Hand Glove', unit: 'pair', quantity: 1, category: 'Stationery Items', costPrice: 64, sellingPrice: 83 },
  { name: 'Green Soft', unit: 'pcs', quantity: 16, category: 'Stationery Items', costPrice: 30, sellingPrice: 39 },
  { name: 'Social Soft', unit: 'pcs', quantity: 35, category: 'Stationery Items', costPrice: 30, sellingPrice: 39 },
  { name: 'Mop', unit: 'pcs', quantity: 1, category: 'Stationery Items', costPrice: 152, sellingPrice: 198 },
  { name: 'Broom', unit: 'pcs', quantity: 7, category: 'Stationery Items', costPrice: 85, sellingPrice: 110 },
  { name: 'File Masriya Gmed', unit: 'pcs', quantity: 9, category: 'Stationery Items', costPrice: 21, sellingPrice: 28 },
  { name: 'Dot Pencil', unit: 'pcs', quantity: 46, category: 'Stationery Items', costPrice: 3, sellingPrice: 4 },
  { name: 'Eraser Rubber', unit: 'pack', quantity: 1, category: 'Stationery Items', costPrice: 212, sellingPrice: 275 },
  { name: 'Protractor', unit: 'pak', quantity: 3, category: 'Stationery Items', costPrice: 127, sellingPrice: 165 },
  { name: 'Rack 9U', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 14808, sellingPrice: 19250 },
  { name: 'UTP Cable CAT 6 H.S Power', unit: 'roll', quantity: 2, category: 'Networking Accessories', costPrice: 11762, sellingPrice: 15290 },
  { name: 'UTP Cable CAT 6 D-link', unit: 'roll', quantity: 2, category: 'Networking Accessories', costPrice: 13962, sellingPrice: 18150 },
  { name: 'Trunking 16x16', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 152, sellingPrice: 198 },
  { name: 'Patch Cord 5m', unit: 'pcs', quantity: 6, category: 'Networking Accessories', costPrice: 381, sellingPrice: 495 },
  { name: 'Patch Cord 3m', unit: 'pcs', quantity: 94, category: 'Networking Accessories', costPrice: 296, sellingPrice: 385 },
  { name: 'Patch Cord 0.5m', unit: 'pcs', quantity: 22, category: 'Networking Accessories', costPrice: 156, sellingPrice: 204 },
  { name: 'Patch Cord 2m', unit: 'pcs', quantity: 172, category: 'Networking Accessories', costPrice: 212, sellingPrice: 275 },
  { name: 'Console Cable VGA Port', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 1100, sellingPrice: 1430 },
  { name: 'Console Cable USB Port', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 1354, sellingPrice: 1760 },
  { name: 'TP-Link Wireless Access Point 3 Ant', unit: 'pcs', quantity: 3, category: 'Networking Accessories', costPrice: 3808, sellingPrice: 4950 },
  { name: 'TP-Link WiFi Range Extender', unit: 'pcs', quantity: 4, category: 'Networking Accessories', costPrice: 3231, sellingPrice: 4180 },
  { name: 'TP-Link AC 1200 Router 4 Antenna', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 4923, sellingPrice: 6380 },
  { name: 'D-link 4Gb Mobile WiFi', unit: 'pcs', quantity: 2, category: 'Networking Accessories', costPrice: 4654, sellingPrice: 6050 },
  { name: 'TP-Link 3G/4G Router', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 3385, sellingPrice: 4400 },
  { name: 'TP-Link Wireless 750 Router', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 4000, sellingPrice: 5280 },
  { name: 'TP-Link WiFi Modem ADSL 2 Antenna', unit: 'pcs', quantity: 3, category: 'Networking Accessories', costPrice: 3231, sellingPrice: 4180 },
  { name: 'TP-Link Access Point Wireless AC 1200 Gigabit', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 2115, sellingPrice: 2750 },
  { name: 'TP-Link USB Wireless Adapter Mini', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 762, sellingPrice: 990 },
  { name: 'USB Wireless Adapter', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 1692, sellingPrice: 2200 },
  { name: 'TP-Link Wireless N PCI Express 150M', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 1769, sellingPrice: 2310 },
  { name: 'Type C Ethernet Adapter', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 808, sellingPrice: 1045 },
  { name: 'USB 3.0 Ethernet Adapter', unit: 'pcs', quantity: 3, category: 'Networking Accessories', costPrice: 719, sellingPrice: 935 },
  { name: 'Switch 24 Port D-Link', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 6000, sellingPrice: 7920 },
  { name: 'Switch D-Link PoE', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 5692, sellingPrice: 7480 },
  { name: 'Switch 8 Port D-Link', unit: 'pcs', quantity: 5, category: 'Networking Accessories', costPrice: 1769, sellingPrice: 2310 },
  { name: 'Patch Panel 48 Port', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 5692, sellingPrice: 7480 },
  { name: 'Patch Panel 24 Port', unit: 'pcs', quantity: 2, category: 'Networking Accessories', costPrice: 3385, sellingPrice: 4400 },
  { name: 'Media Converter Single Mode', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 4654, sellingPrice: 6050 },
  { name: 'Media Converter Multi Mode', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 3808, sellingPrice: 4950 },
  { name: 'USB Ethernet Adapter Windows 7-10', unit: 'pcs', quantity: 3, category: 'Networking Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'Cable Management', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 2192, sellingPrice: 2860 },
  { name: 'Network Fault Finder', unit: 'pcs', quantity: 2, category: 'Networking Accessories', costPrice: 5923, sellingPrice: 7700 },
  { name: 'Crimper', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 550, sellingPrice: 715 },
  { name: 'Crimper D-Link', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 1100, sellingPrice: 1430 },
  { name: 'Network Tester', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 846, sellingPrice: 1100 },
  { name: 'Network Puncher', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 1862, sellingPrice: 2420 },
  { name: 'Power Bank Mi', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 3385, sellingPrice: 4400 },
  { name: 'Wall Outlet Double', unit: 'pcs', quantity: 17, category: 'Networking Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'Wall Outlet Single', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 381, sellingPrice: 495 },
  { name: 'RJ-11', unit: 'pcs', quantity: 101, category: 'Networking Accessories', costPrice: 9, sellingPrice: 12 },
  { name: 'RJ-45', unit: 'pcs', quantity: 1266, category: 'Networking Accessories', costPrice: 7, sellingPrice: 9 },
  { name: 'RJ-45 Jacket', unit: 'pcs', quantity: 813, category: 'Networking Accessories', costPrice: 5, sellingPrice: 7 },
  { name: 'Logitech Pointer', unit: 'pcs', quantity: 1, category: 'Networking Accessories', costPrice: 1523, sellingPrice: 1980 },
  { name: 'Presenter Pointer', unit: 'pcs', quantity: 3, category: 'Networking Accessories', costPrice: 1311, sellingPrice: 1716 },
  { name: 'Screw 8', unit: 'pak', quantity: 5, category: 'Networking Accessories', costPrice: 465, sellingPrice: 605 },
  { name: 'Trunking 40x25 3M', unit: 'pcs', quantity: 100, category: 'Networking Accessories', costPrice: 635, sellingPrice: 825 },
  { name: 'Trunking 40x60 3M', unit: 'pcs', quantity: 103, category: 'Networking Accessories', costPrice: 804, sellingPrice: 1045 },
  { name: 'Total Heat Gun', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 1862, sellingPrice: 2420 },
  { name: 'Boya Mic', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 2962, sellingPrice: 3850 },
  { name: 'Printer Formatter Board 402dn', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 2369, sellingPrice: 3080 },
  { name: 'Printer Formatter Board 400dn', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 2369, sellingPrice: 3080 },
  { name: 'Printer Formatter Board 2055d', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 2369, sellingPrice: 3080 },
  { name: 'Printer Formatter Board 2015d', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 2454, sellingPrice: 3190 },
  { name: 'PCI Express Card USB', unit: 'pcs', quantity: 3, category: 'Other Electronics & Accessories', costPrice: 1192, sellingPrice: 1540 },
  { name: 'PCI Express Card', unit: 'pcs', quantity: 2, category: 'Other Electronics & Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Cooler', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 508, sellingPrice: 660 },
  { name: 'Digital Decoder Popular', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 1269, sellingPrice: 1650 },
  { name: 'Mother Board 3020', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 5923, sellingPrice: 7700 },
  { name: 'Solar Inverter', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 1100, sellingPrice: 1430 },
  { name: 'Hikvision 4 Channel NVR', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 12269, sellingPrice: 15950 },
  { name: 'Camera 4MP Outdoor', unit: 'pcs', quantity: 4, category: 'Other Electronics & Accessories', costPrice: 9731, sellingPrice: 12650 },
  { name: 'Camera 4MP Indoor', unit: 'pcs', quantity: 4, category: 'Other Electronics & Accessories', costPrice: 9731, sellingPrice: 12650 },
  { name: 'Camera 2MP Indoor', unit: 'pcs', quantity: 7, category: 'Other Electronics & Accessories', costPrice: 6346, sellingPrice: 8250 },
  { name: 'Camera 2MP Outdoor', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 6346, sellingPrice: 8250 },
  { name: 'Analog Hikvision with WiFi Kit', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 23692, sellingPrice: 30800 },
  { name: 'DVR 4 Channel Hikvision', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 23692, sellingPrice: 30800 },
  { name: 'DVR 8 Channel Hikvision', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 27077, sellingPrice: 35200 },
  { name: 'Ezviz 360 Camera', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 5500, sellingPrice: 7150 },
  { name: 'Web Camera', unit: 'pcs', quantity: 2, category: 'Other Electronics & Accessories', costPrice: 1058, sellingPrice: 1375 },
  { name: 'Logitech Web Camera 920', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 11115, sellingPrice: 14850 },
  { name: 'Logitech Web Camera 720', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 7692, sellingPrice: 9900 },
  { name: 'USB TV Stick', unit: 'pcs', quantity: 5, category: 'Other Electronics & Accessories', costPrice: 381, sellingPrice: 495 },
  { name: 'Multimeter', unit: 'pcs', quantity: 3, category: 'Other Electronics & Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Camera Battery Canon 5D, 7D', unit: 'pcs', quantity: 2, category: 'Other Electronics & Accessories', costPrice: 3385, sellingPrice: 4400 },
  { name: '9V Adapter', unit: 'pcs', quantity: 10, category: 'Other Electronics & Accessories', costPrice: 550, sellingPrice: 715 },
  { name: '12V Adapter', unit: 'pcs', quantity: 9, category: 'Other Electronics & Accessories', costPrice: 550, sellingPrice: 715 },
  { name: '5V Adapter', unit: 'pcs', quantity: 3, category: 'Other Electronics & Accessories', costPrice: 381, sellingPrice: 495 },
  { name: 'VGA Splitter 4 Channel', unit: 'pcs', quantity: 2, category: 'Other Electronics & Accessories', costPrice: 3385, sellingPrice: 4400 },
  { name: 'Panasonic Battery Camera', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 7192, sellingPrice: 9350 },
  { name: 'Camera Battery Charger Canon 5D', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 2115, sellingPrice: 2750 },
  { name: 'Traveler Charger', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 2369, sellingPrice: 3080 },
  { name: 'Sony Sound Recorder USB Port', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 7692, sellingPrice: 9900 },
  { name: 'Sony Sound Recorder', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 5500, sellingPrice: 7150 },
  { name: 'HDMI Splitter 8 Channel', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 2538, sellingPrice: 3300 },
  { name: 'HDMI Splitter 4 Channel', unit: 'pcs', quantity: 2, category: 'Other Electronics & Accessories', costPrice: 2069, sellingPrice: 2695 },
  { name: 'Headset STN-10', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 1692, sellingPrice: 2200 },
  { name: 'Headset', unit: 'pcs', quantity: 6, category: 'Other Electronics & Accessories', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Headset Wired Welie', unit: 'pcs', quantity: 2, category: 'Other Electronics & Accessories', costPrice: 1100, sellingPrice: 1430 },
  { name: 'Earphone Wireless Rugas', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 1269, sellingPrice: 1650 },
  { name: 'HDMI Extender via CAT 6/CAT5', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 677, sellingPrice: 880 },
  { name: 'Baku Tool Kit', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 212, sellingPrice: 275 },
  { name: 'Universal Adapter 24V/Notebook', unit: 'pcs', quantity: 2, category: 'Other Electronics & Accessories', costPrice: 846, sellingPrice: 1100 },
  { name: 'Camera Bag Small', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 2115, sellingPrice: 2750 },
  { name: 'Laptop Bag CAT Normal', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 6346, sellingPrice: 8250 },
  { name: 'Laptop Bag CAT Original', unit: 'pcs', quantity: 2, category: 'Other Electronics & Accessories', costPrice: 6769, sellingPrice: 8800 },
  { name: 'Laptop Bag Normal', unit: 'pcs', quantity: 4, category: 'Other Electronics & Accessories', costPrice: 2792, sellingPrice: 3630 },
  { name: 'Laptop Side Bag', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 2308, sellingPrice: 2970 },
  { name: 'Laptop Bag Umantu', unit: 'pcs', quantity: 3, category: 'Other Electronics & Accessories', costPrice: 2962, sellingPrice: 3850 },
  { name: 'Stabilizer AVR 5000VA', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 7192, sellingPrice: 9350 },
  { name: 'Dell Screen', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 12692, sellingPrice: 16500 },
  { name: 'Divider Power Source', unit: 'pcs', quantity: 7, category: 'Other Electronics & Accessories', costPrice: 542, sellingPrice: 704 },
  { name: 'PDU', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 1269, sellingPrice: 1650 },
  { name: '9V Battery', unit: 'pcs', quantity: 22, category: 'Other Electronics & Accessories', costPrice: 106, sellingPrice: 138 },
  { name: 'Battery AAA', unit: 'per', quantity: 18, category: 'Other Electronics & Accessories', costPrice: 55, sellingPrice: 72 },
  { name: 'Battery AAA Rechargeable', unit: 'per', quantity: 2, category: 'Other Electronics & Accessories', costPrice: 296, sellingPrice: 385 },
  { name: 'Battery AA', unit: 'per', quantity: 43, category: 'Other Electronics & Accessories', costPrice: 64, sellingPrice: 83 },
  { name: 'Divider Texas', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 745, sellingPrice: 968 },
  { name: 'Divider Guardian Shield 6 Port', unit: 'pcs', quantity: 7, category: 'Other Electronics & Accessories', costPrice: 931, sellingPrice: 1210 },
  { name: 'Divider Power King', unit: 'pcs', quantity: 6, category: 'Other Electronics & Accessories', costPrice: 550, sellingPrice: 715 },
  { name: 'AVR 2000VA', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 5500, sellingPrice: 7150 },
  { name: 'Gato Glories 3000VA', unit: 'pcs', quantity: 2, category: 'Other Electronics & Accessories', costPrice: 16500, sellingPrice: 21450 },
  { name: 'Stabilizer Gato 1500VA', unit: 'pcs', quantity: 3, category: 'Other Electronics & Accessories', costPrice: 2192, sellingPrice: 2860 },
  { name: 'Stabilizer Gato Glories 1000VA', unit: 'pcs', quantity: 1, category: 'Other Electronics & Accessories', costPrice: 4923, sellingPrice: 6380 },
  { name: 'UPS Battery 7V 12A', unit: 'pcs', quantity: 4, category: 'Other Electronics & Accessories', costPrice: 1269, sellingPrice: 1650 },
  { name: 'UPS Battery 7V 9A Small', unit: 'pcs', quantity: 2, category: 'Other Electronics & Accessories', costPrice: 2031, sellingPrice: 2640 },
  { name: 'UPS Battery 9V 12A', unit: 'pcs', quantity: 6, category: 'Other Electronics & Accessories', costPrice: 2792, sellingPrice: 3630 },
  { name: 'C-Size Battery', unit: 'per', quantity: 7, category: 'Other Electronics & Accessories', costPrice: 465, sellingPrice: 605 },
  { name: '26A Toner HP', unit: 'pcs', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 1142, sellingPrice: 1485 },
  { name: '26A Toner Any', unit: 'pcs', quantity: 5, category: 'Toner & Ink Supplies', costPrice: 1227, sellingPrice: 1595 },
  { name: '26A Toner Premium', unit: 'pcs', quantity: 3, category: 'Toner & Ink Supplies', costPrice: 1227, sellingPrice: 1595 },
  { name: 'FX-3 Toner', unit: 'pcs', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 973, sellingPrice: 1265 },
  { name: 'FX-10 Toner', unit: 'pcs', quantity: 1, category: 'Toner & Ink Supplies', costPrice: 973, sellingPrice: 1265 },
  { name: 'C-EXV 14 Toner', unit: 'pcs', quantity: 6, category: 'Toner & Ink Supplies', costPrice: 719, sellingPrice: 935 },
  { name: 'C-EXV 60 Toner', unit: 'pcs', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 719, sellingPrice: 935 },
  { name: 'C-EXV 42 Toner', unit: 'pcs', quantity: 3, category: 'Toner & Ink Supplies', costPrice: 804, sellingPrice: 1045 },
  { name: 'C-EXV 33 Toner', unit: 'pcs', quantity: 10, category: 'Toner & Ink Supplies', costPrice: 885, sellingPrice: 1155 },
  { name: 'Canon Ink', unit: 'set', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 1185, sellingPrice: 1540 },
  { name: 'Toner 85A Any Toner', unit: 'pcs', quantity: 3, category: 'Toner & Ink Supplies', costPrice: 1227, sellingPrice: 1595 },
  { name: 'Epson Ink 70ml', unit: 'set', quantity: 91, category: 'Toner & Ink Supplies', costPrice: 1100, sellingPrice: 1430 },
  { name: 'Powder 1kg Toner', unit: 'pcs', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 1015, sellingPrice: 1320 },
  { name: 'Genies 80A', unit: 'pcs', quantity: 4, category: 'Toner & Ink Supplies', costPrice: 465, sellingPrice: 605 },
  { name: 'Genies 49A', unit: 'pcs', quantity: 4, category: 'Toner & Ink Supplies', costPrice: 465, sellingPrice: 605 },
  { name: '12A Toner Any', unit: 'pcs', quantity: 1, category: 'Toner & Ink Supplies', costPrice: 1227, sellingPrice: 1595 },
  { name: '80A Toner Any', unit: 'pcs', quantity: 8, category: 'Toner & Ink Supplies', costPrice: 1227, sellingPrice: 1595 },
  { name: '37A Toner Any', unit: 'pcs', quantity: 1, category: 'Toner & Ink Supplies', costPrice: 2285, sellingPrice: 2970 },
  { name: '17A Toner Any', unit: 'pcs', quantity: 3, category: 'Toner & Ink Supplies', costPrice: 1227, sellingPrice: 1595 },
  { name: 'Drum Unit 19A', unit: 'pcs', quantity: 1, category: 'Toner & Ink Supplies', costPrice: 1523, sellingPrice: 1980 },
  { name: '59A Toner Any without Chip', unit: 'pcs', quantity: 4, category: 'Toner & Ink Supplies', costPrice: 2242, sellingPrice: 2915 },
  { name: '305A Toner Any', unit: 'set', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 2385, sellingPrice: 3080 },
  { name: '151A Toner No Chip', unit: 'pcs', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 2385, sellingPrice: 3080 },
  { name: 'MX-315 Toner', unit: 'pcs', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 2385, sellingPrice: 3080 },
  { name: 'TN 3417 Toner', unit: 'pcs', quantity: 1, category: 'Toner & Ink Supplies', costPrice: 1015, sellingPrice: 1320 },
  { name: 'TK 6325 Toner', unit: 'pcs', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 1650, sellingPrice: 2145 },
  { name: 'TK-4105 Toner', unit: 'pcs', quantity: 1, category: 'Toner & Ink Supplies', costPrice: 1992, sellingPrice: 2585 },
  { name: '15A Toner Nanodas', unit: 'pcs', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 635, sellingPrice: 825 },
  { name: '83A Toner Any', unit: 'pcs', quantity: 1, category: 'Toner & Ink Supplies', costPrice: 1227, sellingPrice: 1595 },
  { name: '05A Toner Any', unit: 'pcs', quantity: 3, category: 'Toner & Ink Supplies', costPrice: 1269, sellingPrice: 1650 },
  { name: '05A Toner HP', unit: 'pcs', quantity: 10, category: 'Toner & Ink Supplies', costPrice: 1058, sellingPrice: 1375 },
  { name: '53A Toner HP', unit: 'pcs', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 973, sellingPrice: 1265 },
  { name: '106A Toner Any', unit: 'pcs', quantity: 1, category: 'Toner & Ink Supplies', costPrice: 1946, sellingPrice: 2530 },
  { name: '107A Toner Any', unit: 'pcs', quantity: 5, category: 'Toner & Ink Supplies', costPrice: 1946, sellingPrice: 2530 },
  { name: '725A Toner Any', unit: 'pcs', quantity: 2, category: 'Toner & Ink Supplies', costPrice: 1058, sellingPrice: 1375 },
  { name: '728A Toner Any', unit: 'pcs', quantity: 4, category: 'Toner & Ink Supplies', costPrice: 1058, sellingPrice: 1375 },
  { name: 'Master 7608 Toner', unit: 'Pcs', quantity: 1, category: 'Toner & Ink Supplies', costPrice: 750, sellingPrice: 825 },
  { name: 'Master 4363 Toner', unit: 'Pcs', quantity: 9, category: 'Toner & Ink Supplies', costPrice: 650, sellingPrice: 715 },
  { name: 'Lexmark 410 Toner', unit: 'pcs', quantity: 1, category: 'Toner & Ink Supplies', costPrice: 1650, sellingPrice: 1815 },
];

async function main() {
  console.log('🌱 Seeding database with inventory data...');
  
  for (const item of inventoryData) {
    try {
      // Check if product exists by name
      const existing = await prisma.product.findFirst({
        where: { name: item.name },
      });

      let product;
      if (existing) {
        // Determine piecesPerUnit for update
        const unitLower = (item.unit || existing.unit || 'pcs').toLowerCase();
        let piecesPerUnit = existing.piecesPerUnit || 1;
        if (!existing.piecesPerUnit || existing.piecesPerUnit === 1) {
          if (unitLower === 'pack') piecesPerUnit = 10;
          else if (unitLower === 'reem') piecesPerUnit = 500;
          else if (unitLower === 'set') piecesPerUnit = 1;
          else piecesPerUnit = 1;
        }
        
        // Update existing product
        product = await prisma.product.update({
          where: { id: existing.id },
          data: {
            unit: item.unit || existing.unit || 'pcs',
            piecesPerUnit: piecesPerUnit as number,
            stockQty: { increment: item.quantity },
            costPrice: new Decimal(item.costPrice),
            sellingPrice: new Decimal(item.sellingPrice),
            category: item.category,
          },
        });
      } else {
        // Create new product
        // Determine piecesPerUnit based on unit type
        // Common defaults: pack=10, reem=500, set=varies, pcs=1
        const unitLower = (item.unit || 'pcs').toLowerCase();
        let piecesPerUnit = 1;
        if (unitLower === 'pack') piecesPerUnit = 10; // Default 10 pieces per pack
        else if (unitLower === 'reem') piecesPerUnit = 500; // Default 500 sheets per reem
        else if (unitLower === 'set') piecesPerUnit = 1; // Sets vary, default 1
        else if (unitLower === 'pcs' || unitLower === 'pc' || unitLower === 'piece') piecesPerUnit = 1;
        // Can be updated later in admin panel
        
        product = await prisma.product.create({
          data: {
            name: item.name,
            unit: item.unit || 'pcs', // Default to 'pcs' if not provided
            piecesPerUnit: piecesPerUnit as number,
            stockQty: item.quantity,
            costPrice: new Decimal(item.costPrice),
            sellingPrice: new Decimal(item.sellingPrice), // Price is per unit (pack/reem/pcs)
            category: item.category,
            lowStockAlert: 5,
            showOnWebsite: true, // Show on website by default
            isNew: false,
          },
        });
      }

      // Create stock entry
      await prisma.stockEntry.create({
        data: {
          productId: product.id,
          quantity: item.quantity,
          costPrice: new Decimal(item.costPrice),
          supplierName: 'Initial Stock',
          status: 'FULLY_PAID',
        },
      });
    } catch (error) {
      console.error(`❌ Failed to seed item: ${item.name}`, error);
    }
  }

  console.log('✅ Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });